### ISSUE TITLE
Replace Empty State Image

### ISSUE THREAD

**Issue by erinesullivan** [mlibrary/search.account#142]
> Decide on image for empty state messages **USE STACK OF BOOKS**

[https://umich.app.box.com/folder/138063277691?utm_campaign=collab%20auto%20accept%20user&utm_medium=email&utm_source=trans](https://umich.app.box.com/folder/138063277691?utm_campaign=collab%20auto%20accept%20user&utm_medium=email&utm_source=trans)

**Comment by jonearley** [comment]
**Status update:** I was granted access to view the image on Box. It has white space around the graphic which looks like positioning, but that won't be useful when it's added in browser. I added a comment for it to be trimmed in Box and added the `blocked` tag.
